version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: teste
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3307:3306

